version: "2.1"
services:
  postgresql:
    image: postgres:10
    ports:
      - 5432:5432
    environment:
      - PGDATA=/postgresql
      - PG_PASSWORD=gu410
    volumes:
      - ./tmp/system/postgresql:/postgresql