version: "2.1"
services:
  postgresql:
    image: postgres:10
    environment:
      - PGDATA=/postgresql
      - PG_PASSWORD=gu410
    volumes:
      - ./tmp/system/postgresql:/postgresql
    healthcheck:
      test: "pg_isready -h localhost -p 5432 -q -U postgres"
      interval: 3s
      timeout: 5s
      retries: 5
  minas:
    build: .
    ports:
      - 9000:9000
    depends_on:
      postgresql:
        condition: service_healthy